name: "NIST Software Portal"
author: "NIST Open Source <opensource@nist.gov>"
title: NIST Software Portal
description: "National Institute of Standards and Technology"
#remote_theme: LLNL/Jekyll-LLNL-Theme
theme: usnistgov/nist-software-theme

url: "https://github.com/faical-yannick-congo.github.io/code-portal"
repo_url: "https://github.com/faical-yannick-congo/code-portal"

# LLNL Piwik Analytics https://analytics.llnl.gov
#piwik_id: 250

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
#twitter:
#  username: llnl_opensource

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: faical-yannick-congo/code-portal
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
